import { exportPathMap } from '@/next.config'
import './globals.css'
import { Header } from './components/header'
import {font} from './font'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <head>
        <title>My first app</title>
      </head>
      <body>
        <Header></Header>
        {children}
      </body>
    </html>
  )
}
